In [1]:
#implementation of KNN
import numpy as np
f= open("D:/Ashwath/NS_Trainings/MyStuff/knndata.txt")
header = f.readline()
lines = f.readlines()
info=[]
for line in lines:
    w = line.strip().split(",") 
    ins=[int(v) for v in w[:-1]]
    info.append((np.array(ins),w[-1])) 
for v in info:
    print(v)

(array([10, 20]), 'm')
(array([10, 15]), 'f')
(array([ 9, 14]), 'f')
(array([10, 13]), 'f')
(array([11, 22]), 'm')
(array([11, 16]), 'f')
(array([12, 25]), 'm')
(array([12, 16]), 'f')
(array([15, 40]), 'm')
(array([15, 21]), 'f')
(array([14, 38]), 'm')
(array([14, 20]), 'f')
(array([14, 21]), 'f')
(array([14, 22]), 'f')
(array([14, 21]), 'f')
(array([13, 20]), 'f')
(array([14, 23]), 'f')


In [2]:
#finding distance
new = np.array([20,35])
dist =[]
for v in info:
    attr = v[0]
    d = ((new - attr)**2).sum()**0.5 
    dist.append((d,v[1]))
dist.sort()
for d in dist:
    print(d)

(np.float64(6.708203932499369), 'm')
(np.float64(7.0710678118654755), 'm')
(np.float64(12.806248474865697), 'm')
(np.float64(13.416407864998739), 'f')
(np.float64(14.317821063276353), 'f')
(np.float64(14.866068747318506), 'f')
(np.float64(15.231546211727817), 'f')
(np.float64(15.231546211727817), 'f')
(np.float64(15.811388300841896), 'm')
(np.float64(16.15549442140351), 'f')
(np.float64(16.55294535724685), 'f')
(np.float64(18.027756377319946), 'm')
(np.float64(20.615528128088304), 'f')
(np.float64(21.02379604162864), 'f')
(np.float64(22.360679774997898), 'f')
(np.float64(23.706539182259394), 'f')
(np.float64(24.166091947189145), 'f')


In [ ]:
#finding frequency of classifiers
k = 5   # taking 5 as nearst nieghbours
x = dist[:k]
freq = {}        
for d in x:
    if freq.get(d[1])==None: 
        freq[d[1]]=1       
    else:
        freq[d[1]]+=1
print(freq)

In [ ]:
#define predict function
def predict(data,new): 
    dist =[]
    for v in data:
        attr = v[0]
        d = ((new - attr)**2).sum()**0.5
        #sqrt[(x1 - x2)^2 + (y1 - y2)^2]  
        dist.append((d,v[1]))
    dist.sort()    
        
    k = 5   # taking 5 as nearst nieghbours
    x = dist[:k]       
        
    freq = {}
    for d in x:
        if freq.get(d[1])==None:
            freq[d[1]]=1
        else:
            freq[d[1]]+=1
    return (freq)

In [ ]:
newdata = np.array([20,35])
prevals = predict(info,newdata)
print (prevals)

In [ ]:
#implementation of KNC :
infor = {}
for v in info:
    attr = v[0]
    k = v[1]                  
    if infor.get(k)==None:         
        infor[k] = [attr]        
    else:                           
        infor[k].append(attr)           
print(infor)                       

ins={}
for k in infor:
    ins[k]=np.array(infor[k])
print(ins)

In [ ]:
centorids = {}
for k in ins:
    v = ins[k]
    centorids[k]=v.mean(axis=0)
print (centorids)

In [ ]:
new = np.array([20,35])
ndist = {}
for k in centorids:
    d=((centorids[k]-new)**2).sum()**0.5
    ndist[k]=d
print (ndist)