In [ ]:
import numpy as np

def predict(x,b):
    return x.dot(b)

def mse(y,ycap):
    return((y-ycap)**2).mean()

def derivative(x,y,beta):
    ycap = predict(x,beta)
    return(x.T.dot(y-ycap))/y.size

#standard deviation
def sd(x):     
    return (((x-x.mean())**2).sum() / (x.size-1))**0.5 

#standard scaling
def scale(x):  
    return (x-x.mean())/sd(x)
   
def train(x,y,iter,alpha,conv = 0.0000001):
    beta = np.c_[np.zeros(x.shape[1])]
    perr = 0
    j = 0
    for i in range(iter):
        ycap = predict(x,beta)
        cerr = mse(y,ycap)
        if i % 50 == 0:
            print("Current Error ",cerr)
        diff = np.abs(perr-cerr)
        if diff <= conv:
            print("Training Completed ",i+1, "iterations")
            j = 1
            break
        delta = derivative(x,y,beta)
        beta = beta + alpha * delta
        perr = cerr
    if j == 0:
        print("Training not completed")
    return beta

def scalematrix(x):
    ncol=x.shape[1]   #1,60,5.5,40  x = (3,5) x[1]  =5
    for i in range(ncol):  
        if i == 0:
            continue
        c = x[:,i]
        x[:,i] = scale(c) 
    return x                 

def accuarcy(y,ycap,closeness):
    de = 100-closeness
    d = np.abs((y-ycap)/y)*100
    pcnt = d[d<=de].size
    n=y.size
    return pcnt/n*100

In [ ]:
f=open("D:/Ashwath/NS_Trainings/MyStuff/paitents.txt")
header=f.readline()
lines=f.readlines()
#print(lines)
age=[]
wgt=[]
hgt=[]
chol=[]
for line in lines:
    l=line.strip().split(',')
    #print(l)
    a=float(l[2])
    w=float(l[3])
    h=float(l[-2])
    ch=float(l[-1])
    age.append(a)
    wgt.append(w)
    hgt.append(h)
    chol.append(ch)
print(age,wgt,hgt,chol)

ones=np.ones(len(lines))
X=np.c_[ones,age,wgt,hgt] #input matrix
print(X)

#print(chol)
Y=np.c_[chol] #label / output matrix
print(Y)

In [ ]:
age=np.array(age)
hgt=np.array(hgt)
wgt=np.array(wgt)
chol=np.array(chol)

mage = age.mean()
mwgt = wgt.mean()
mhgt = hgt.mean()
mchol=chol.mean()

sage = sd(age)
swgt = sd(wgt)
shgt = sd(hgt)
schol = sd(chol)

In [ ]:
print("Before Scaling :")
print(X)
print(Y)
print("="*50)
print("After Scaling :")
X = scalematrix(X)
Ys = scale(Y)
print(X)
print(Ys)

In [ ]:
theta = train(X,Ys,10000,0.05)

In [ ]:
print(theta)

In [ ]:
ycap = predict(X,theta)
print("============================")
print (ycap)

In [ ]:
#unscaled prediction

# def scale(x):  
#     return (x-x.mean())/sd(x)

uycap = ycap * schol + mchol
print(uycap)

In [ ]:
[[60.]
 [62.]
 [60.]
 [80.]
 [85.]
 [60.]]

In [ ]:
print(accuarcy(Y,uycap,90))

In [ ]:
# prediction for new data
fo=open("D:/Ashwath/NS_Trainings/MyStuff/Newpaitents.txt")
header=fo.readline()
data=fo.readlines()
age=[]
wgt=[]
hgt=[]
for d in data:
    l=d.strip().split(',')
    a=float(l[2])
    w=float(l[3])
    h=float(l[-1])
    age.append(a)
    wgt.append(w)
    hgt.append(h)

age=np.array(age)
wgt=np.array(wgt)
hgt=np.array(hgt)

O=np.ones(len(data))

print("Unscaled input matrix")
uX=np.c_[O,age,wgt,hgt]
print(uX)

# Sp = scalematrix(uX)
# print(Sp)

In [ ]:
A=(age-mage)/sage
W=(wgt-mwgt)/swgt
H=(hgt-mhgt)/shgt

P=np.c_[O,A,W,H]

print("Input Matrix : ")
print(P)

In [ ]:
yc = predict(P,theta)

print("Scaled prediction : ")
print(yc)

In [ ]:
unspredict = yc * schol + mchol

print("Unscaled predictions :")
print(unspredict)

<h3>Scikit Learn (SKLearn) Library :</h3>

Scikit-learn is an open source data analysis library, and the gold standard for Machine Learning (ML) in the Python ecosystem. Key concepts and features include:

Algorithmic decision-making methods, including:
Classification: identifying and categorizing data based on patterns.
Regression: predicting or projecting data values based on the average mean of existing and planned data.

Clustering: automatic grouping of similar data into datasets.
Algorithms that support predictive analysis ranging from simple linear regression to neural network pattern recognition.

Interoperability with NumPy, pandas, and matplotlib libraries.
ML is a technology that enables computers to learn from input data and to build/train a predictive model without explicit programming. ML is a subset of Artificial Intelligence (AI). 

In [ ]:
#training the model using libray : sklearn (scikit learn)
from sklearn.linear_model import LinearRegression
model = LinearRegression() 
model.fit(X,Y)
lrycap=model.predict(X)
print(lrycap)

In [ ]:
[[56.45855918]
 [62.65952646]
 [62.41421259]
 [79.9129109 ]
 [84.14807399]
 [61.40671688]]

In [ ]:
lracc = accuarcy(Y,lrycap,90)
print("Accuracy of Linear Regression : ",lracc)
print(lrycap)
#print(Y)

In [ ]:
#testing data

lrycap1=model.predict(P)
print (lrycap1)

In [ ]:
Unscaled predictions :
[[61.83751721]
 [62.72260707]
 [66.28274036]]

In [ ]:
a = 5000
b = 5
a1 = sd(a)
#print(scale(a))
#print(scale(b))

<h3>Scikit Learn (SKLearn) Library :</h3>

Scikit-learn is an open source data analysis library, and the gold standard for Machine Learning (ML) in the Python ecosystem. Key concepts and features include:

Algorithmic decision-making methods, including:
Classification: identifying and categorizing data based on patterns.
Regression: predicting or projecting data values based on the average mean of existing and planned data.

Clustering: automatic grouping of similar data into datasets.
Algorithms that support predictive analysis ranging from simple linear regression to neural network pattern recognition.

Interoperability with NumPy, pandas, and matplotlib libraries.
ML is a technology that enables computers to learn from input data and to build/train a predictive model without explicit programming. ML is a subset of Artificial Intelligence (AI). 